# Training parameters
seed: [43, 91, 17] # overwritten in main.py 
batch_size: 256
learning_rate: 0.05
momentum: 0.9
num_epochs: 75

# Model configuration
models_dir: ../models
vgg_config: vgg_config.json  

# Metrics
metrics:
  # - acc
  # - ece
  # - squared_euclidean_norm
  # - max_hessian_eigenvalue
  # - hessian_trace
  # - fisher_rao_norm
  - relative_flatness
  # - IGS
#  - pacbayes_flatness

# Other directories
config_dir: ../configs

cifar_dir: ../data/cifar

wandb:
  experiment_name: '' # overwritten in main.py
  project: 'VGG19_CIFAR10_FINAL'
  entity: 'r252_project'

# Sharpness calculation
sharpness_dataset_size: 7500
sharpness_batch_size: 7500